### ISSUE TITLE
How do I use this with Jade?

### ISSUE THREAD

**Issue by vonKristoff** [evil-icons/gulp-evil-icons#1]
Lol, cannot work out how to integrate this from your example.
My Jade part of my gulp file looks a little like this ..

gulp.task('jade',function() {
  gulp.src('./jade')
    .pipe(jade())
    .pipe(evil-icons())
    .pipe(gulp.dest('../'))
    .pipe(refresh())
})

Your example seems to want to process on the index.html .. would I have to do this after the jade has processed? Also the path inclusion of the assets in the example doesnt match the one built by npm. Or am I incorrect because the evil-icons hasnt processed. If you can give me a hand, I may understand what the plugin is actually trying to do. Thanks!

**Comment by madyankin** [comment]
You are using the `-` character in your code, which is not allowed by javascript in identifiers. Actually, I've used this plugin in our website, so you can see the example — https://github.com/outpunk/evil-icons/blob/gh-pages/Gulpfile.coffee#L53. Anyway, if you can't get it work, let me know, please.

**Comment by vonKristoff** [comment]
Ha! I was just using psudo code when i used evil-icons .. in my real code i
do omit the hyphen.
Thanks for the link. But you pass Vars into the Jade compiler (and as this
isnt documented it becomes part of the confusion).
My icon tags in Jade arent converted at all so something isnt working.

Another very very basic thing that is different is that upon npm install,
the path is like so ..
node_modules/gulp-evil-icons/node_modules/evil-icons/.. Should I include
npm install evil-icons as well as the gulp-evil-icons plugin!? Or do I copy
the contents of evil-icons to the same destination path as my index.html ..

Thanks for your help .. I cannot believe I am struggling with this!

On 9 January 2015 at 18:54, Alexander Madyankin notifications@github.com
wrote:

> You are using the - character in your code, which is not allowed by
> javascript in identifiers. Actually, I've used this plugin in our website,
> so you can see the example —
> https://github.com/outpunk/evil-icons/blob/gh-pages/Gulpfile.coffee#L53.
> Anyway, if you can't get it work, let me know, please.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/outpunk/gulp-evil-icons/issues/1#issuecomment-69380250
> .

## 

best,
Jean-Christophe Nicolas ../

**Comment by madyankin** [comment]
Try to replace `gulp.src('./jade')` with `gulp.src('./jade/*')`.

**Comment by madyankin** [comment]
Oh, and you haven't to do `npm install evil-icons` separately. It's enough to install only gulp-evil-icons.

**Comment by vonKristoff** [comment]
Thanks - yes your method does work (to pipe evilicons after jade). 
I was overcomplicating things and trying to compile the icons browser side, with browserify. After a clean run - all plays nicely. Mega thanks to the example gulp file btw!
