### ISSUE TITLE
Sorry more Jade and Evil Icons questions

### ISSUE THREAD

**Issue by gandhiShepard** [evil-icons/gulp-evil-icons#2]
I problem that I have is with Jade nesting the path elements. This will show the outline of the eye, but not the inside of the eye. I can't figure out how to keep the paths from nesting. I added some screenshots. I'm also using Stylus. I'm not sure if that matters. Thanks! These are freaking awesome!

![screen shot 2015-01-11 at 9 44 44 am](https://cloud.githubusercontent.com/assets/8546059/5695758/10019eae-9977-11e4-92af-b478cf3bdde3.jpg)
![screen shot 2015-01-11 at 9 44 14 am](https://cloud.githubusercontent.com/assets/8546059/5695759/1001d09a-9977-11e4-8c3c-73844fc9e7b3.jpg)

**Comment by gandhiShepard** [comment]
The simple chevron displays fine, but the pupil inside the eye is not.

**Comment by madyankin** [comment]
You have to invoke gulp-evil-icons after jade, like this:

``` js
gulp.task('default', function () {
  return gulp.src('src/index.jade')
    .pipe(jade())
    .pipe(evilIcons())
    .pipe(gulp.dest('build'));
});
```

**Comment by gandhiShepard** [comment]
I am. Here is the task that I'm running.

gulp.task('html', ['clean:html'], function() {
  return gulp.src('src/index.jade')
    .pipe(isDist ? through() : plumber())
    .pipe(jade({ pretty: true }))
    .pipe(evilIcons())
    .pipe(rename('index.html'))
    .pipe(gulp.dest('dist'))
    .pipe(reload({stream:true}));
});

**Comment by madyankin** [comment]
I'll check this, thank you for the report.

**Comment by gandhiShepard** [comment]
For what it's worth, I'm making a presentation using [Bespoke.js](http://markdalgleish.com/projects/bespoke.js/). This is the environment that I'm using Evil Icons in.

**Comment by gandhiShepard** [comment]
I'm using it in Jade like this:

```
li 
  icon(name="ei-heart" size="s") 
  a(href="http://evil-icons.io/") Evil Icons
```

**Comment by madyankin** [comment]
I can't reproduce this http://img.madyankin.name/jI2Xz.png.
Could you show me a minimal example of your jade code (with doctype and such things)?

**Comment by madyankin** [comment]
And it would be nice to see the compiled html.

**Comment by gandhiShepard** [comment]
Here you go:

Compiled Jade file(html) : https://gist.github.com/gandhiShepard/e1cd48fba2deef95bdf6
Jade source file: https://gist.github.com/gandhiShepard/cfdc493af663b0a43fea

**Comment by madyankin** [comment]
I've fixed this, thank you for the report and for your help. The new version is accessible in npm.

**Comment by gandhiShepard** [comment]
What was the issue? Just curios incase I run into something similar in jade.

**Comment by gandhiShepard** [comment]
ALSO...thanks! Stay awesome!

**Comment by madyankin** [comment]
Cheerio, the html parser, was too smart to break the output html. I've replaced it with a couple of good old regular expressions.
